os:
  - osx

language: node_js

node_js:
  - '8'

branches:
  only:
    - master

before_install:
    - chmod +x travis-build.sh

before_script:
    - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start

script: ./travis-build.sh

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change