os:
  - linux
  - osx

language: node_js

node_js:
  - '6'

branches:
  only:
    - master

script: ./travis-build.sh

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change